// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: database.proto

#include "database.pb.h"
#include "database.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>
#include <grpcpp/ports_def.inc>
namespace bpsndb {

static const char* DatabaseEngine_method_names[] = {
  "/bpsndb.DatabaseEngine/Execute",
};

std::unique_ptr< DatabaseEngine::Stub> DatabaseEngine::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< DatabaseEngine::Stub> stub(new DatabaseEngine::Stub(channel, options));
  return stub;
}

DatabaseEngine::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_Execute_(DatabaseEngine_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status DatabaseEngine::Stub::Execute(::grpc::ClientContext* context, const ::bpsndb::CommandRequest& request, ::bpsndb::CommandResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::bpsndb::CommandRequest, ::bpsndb::CommandResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_Execute_, context, request, response);
}

void DatabaseEngine::Stub::async::Execute(::grpc::ClientContext* context, const ::bpsndb::CommandRequest* request, ::bpsndb::CommandResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::bpsndb::CommandRequest, ::bpsndb::CommandResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Execute_, context, request, response, std::move(f));
}

void DatabaseEngine::Stub::async::Execute(::grpc::ClientContext* context, const ::bpsndb::CommandRequest* request, ::bpsndb::CommandResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Execute_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::bpsndb::CommandResponse>* DatabaseEngine::Stub::PrepareAsyncExecuteRaw(::grpc::ClientContext* context, const ::bpsndb::CommandRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::bpsndb::CommandResponse, ::bpsndb::CommandRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_Execute_, context, request);
}

::grpc::ClientAsyncResponseReader< ::bpsndb::CommandResponse>* DatabaseEngine::Stub::AsyncExecuteRaw(::grpc::ClientContext* context, const ::bpsndb::CommandRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncExecuteRaw(context, request, cq);
  result->StartCall();
  return result;
}

DatabaseEngine::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      DatabaseEngine_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< DatabaseEngine::Service, ::bpsndb::CommandRequest, ::bpsndb::CommandResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](DatabaseEngine::Service* service,
             ::grpc::ServerContext* ctx,
             const ::bpsndb::CommandRequest* req,
             ::bpsndb::CommandResponse* resp) {
               return service->Execute(ctx, req, resp);
             }, this)));
}

DatabaseEngine::Service::~Service() {
}

::grpc::Status DatabaseEngine::Service::Execute(::grpc::ServerContext* context, const ::bpsndb::CommandRequest* request, ::bpsndb::CommandResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace bpsndb
#include <grpcpp/ports_undef.inc>

