// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.1
// source: database.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	DatabaseEngine_Execute_FullMethodName = "/bpsndb.DatabaseEngine/Execute"
)

// DatabaseEngineClient is the client API for DatabaseEngine service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DatabaseEngineClient interface {
	Execute(ctx context.Context, in *CommandRequest, opts ...grpc.CallOption) (*CommandResponse, error)
}

type databaseEngineClient struct {
	cc grpc.ClientConnInterface
}

func NewDatabaseEngineClient(cc grpc.ClientConnInterface) DatabaseEngineClient {
	return &databaseEngineClient{cc}
}

func (c *databaseEngineClient) Execute(ctx context.Context, in *CommandRequest, opts ...grpc.CallOption) (*CommandResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommandResponse)
	err := c.cc.Invoke(ctx, DatabaseEngine_Execute_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DatabaseEngineServer is the server API for DatabaseEngine service.
// All implementations must embed UnimplementedDatabaseEngineServer
// for forward compatibility.
type DatabaseEngineServer interface {
	Execute(context.Context, *CommandRequest) (*CommandResponse, error)
	mustEmbedUnimplementedDatabaseEngineServer()
}

// UnimplementedDatabaseEngineServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDatabaseEngineServer struct{}

func (UnimplementedDatabaseEngineServer) Execute(context.Context, *CommandRequest) (*CommandResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Execute not implemented")
}
func (UnimplementedDatabaseEngineServer) mustEmbedUnimplementedDatabaseEngineServer() {}
func (UnimplementedDatabaseEngineServer) testEmbeddedByValue()                        {}

// UnsafeDatabaseEngineServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DatabaseEngineServer will
// result in compilation errors.
type UnsafeDatabaseEngineServer interface {
	mustEmbedUnimplementedDatabaseEngineServer()
}

func RegisterDatabaseEngineServer(s grpc.ServiceRegistrar, srv DatabaseEngineServer) {
	// If the following call panics, it indicates UnimplementedDatabaseEngineServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DatabaseEngine_ServiceDesc, srv)
}

func _DatabaseEngine_Execute_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CommandRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DatabaseEngineServer).Execute(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DatabaseEngine_Execute_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DatabaseEngineServer).Execute(ctx, req.(*CommandRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DatabaseEngine_ServiceDesc is the grpc.ServiceDesc for DatabaseEngine service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DatabaseEngine_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "bpsndb.DatabaseEngine",
	HandlerType: (*DatabaseEngineServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Execute",
			Handler:    _DatabaseEngine_Execute_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "database.proto",
}
