// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: database.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CommandResponse_Status int32

const (
	CommandResponse_SUCCESS    CommandResponse_Status = 0
	CommandResponse_FAILURE    CommandResponse_Status = 1
	CommandResponse_TABLE_FULL CommandResponse_Status = 2
)

// Enum value maps for CommandResponse_Status.
var (
	CommandResponse_Status_name = map[int32]string{
		0: "SUCCESS",
		1: "FAILURE",
		2: "TABLE_FULL",
	}
	CommandResponse_Status_value = map[string]int32{
		"SUCCESS":    0,
		"FAILURE":    1,
		"TABLE_FULL": 2,
	}
)

func (x CommandResponse_Status) Enum() *CommandResponse_Status {
	p := new(CommandResponse_Status)
	*p = x
	return p
}

func (x CommandResponse_Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CommandResponse_Status) Descriptor() protoreflect.EnumDescriptor {
	return file_database_proto_enumTypes[0].Descriptor()
}

func (CommandResponse_Status) Type() protoreflect.EnumType {
	return &file_database_proto_enumTypes[0]
}

func (x CommandResponse_Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CommandResponse_Status.Descriptor instead.
func (CommandResponse_Status) EnumDescriptor() ([]byte, []int) {
	return file_database_proto_rawDescGZIP(), []int{2, 0}
}

// The message representing a database row
type Row struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Email         string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Row) Reset() {
	*x = Row{}
	mi := &file_database_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Row) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Row) ProtoMessage() {}

func (x *Row) ProtoReflect() protoreflect.Message {
	mi := &file_database_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Row.ProtoReflect.Descriptor instead.
func (*Row) Descriptor() ([]byte, []int) {
	return file_database_proto_rawDescGZIP(), []int{0}
}

func (x *Row) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Row) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *Row) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

// Request for executing a command
type CommandRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Statement     string                 `protobuf:"bytes,1,opt,name=statement,proto3" json:"statement,omitempty"` // e.g. insert 1 bhanu b@mail.com or select
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommandRequest) Reset() {
	*x = CommandRequest{}
	mi := &file_database_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommandRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandRequest) ProtoMessage() {}

func (x *CommandRequest) ProtoReflect() protoreflect.Message {
	mi := &file_database_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandRequest.ProtoReflect.Descriptor instead.
func (*CommandRequest) Descriptor() ([]byte, []int) {
	return file_database_proto_rawDescGZIP(), []int{1}
}

func (x *CommandRequest) GetStatement() string {
	if x != nil {
		return x.Statement
	}
	return ""
}

// Response from the engine
type CommandResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        CommandResponse_Status `protobuf:"varint,1,opt,name=status,proto3,enum=bpsndb.CommandResponse_Status" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Rows          []*Row                 `protobuf:"bytes,3,rep,name=rows,proto3" json:"rows,omitempty"` // For SELECT queries
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommandResponse) Reset() {
	*x = CommandResponse{}
	mi := &file_database_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommandResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandResponse) ProtoMessage() {}

func (x *CommandResponse) ProtoReflect() protoreflect.Message {
	mi := &file_database_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandResponse.ProtoReflect.Descriptor instead.
func (*CommandResponse) Descriptor() ([]byte, []int) {
	return file_database_proto_rawDescGZIP(), []int{2}
}

func (x *CommandResponse) GetStatus() CommandResponse_Status {
	if x != nil {
		return x.Status
	}
	return CommandResponse_SUCCESS
}

func (x *CommandResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *CommandResponse) GetRows() []*Row {
	if x != nil {
		return x.Rows
	}
	return nil
}

var File_database_proto protoreflect.FileDescriptor

const file_database_proto_rawDesc = "" +
	"\n" +
	"\x0edatabase.proto\x12\x06bpsndb\"G\n" +
	"\x03Row\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\".\n" +
	"\x0eCommandRequest\x12\x1c\n" +
	"\tstatement\x18\x01 \x01(\tR\tstatement\"\xb8\x01\n" +
	"\x0fCommandResponse\x126\n" +
	"\x06status\x18\x01 \x01(\x0e2\x1e.bpsndb.CommandResponse.StatusR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1f\n" +
	"\x04rows\x18\x03 \x03(\v2\v.bpsndb.RowR\x04rows\"2\n" +
	"\x06Status\x12\v\n" +
	"\aSUCCESS\x10\x00\x12\v\n" +
	"\aFAILURE\x10\x01\x12\x0e\n" +
	"\n" +
	"TABLE_FULL\x10\x022L\n" +
	"\x0eDatabaseEngine\x12:\n" +
	"\aExecute\x12\x16.bpsndb.CommandRequest\x1a\x17.bpsndb.CommandResponseB\tZ\a./protob\x06proto3"

var (
	file_database_proto_rawDescOnce sync.Once
	file_database_proto_rawDescData []byte
)

func file_database_proto_rawDescGZIP() []byte {
	file_database_proto_rawDescOnce.Do(func() {
		file_database_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_database_proto_rawDesc), len(file_database_proto_rawDesc)))
	})
	return file_database_proto_rawDescData
}

var file_database_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_database_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_database_proto_goTypes = []any{
	(CommandResponse_Status)(0), // 0: bpsndb.CommandResponse.Status
	(*Row)(nil),                 // 1: bpsndb.Row
	(*CommandRequest)(nil),      // 2: bpsndb.CommandRequest
	(*CommandResponse)(nil),     // 3: bpsndb.CommandResponse
}
var file_database_proto_depIdxs = []int32{
	0, // 0: bpsndb.CommandResponse.status:type_name -> bpsndb.CommandResponse.Status
	1, // 1: bpsndb.CommandResponse.rows:type_name -> bpsndb.Row
	2, // 2: bpsndb.DatabaseEngine.Execute:input_type -> bpsndb.CommandRequest
	3, // 3: bpsndb.DatabaseEngine.Execute:output_type -> bpsndb.CommandResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_database_proto_init() }
func file_database_proto_init() {
	if File_database_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_database_proto_rawDesc), len(file_database_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_database_proto_goTypes,
		DependencyIndexes: file_database_proto_depIdxs,
		EnumInfos:         file_database_proto_enumTypes,
		MessageInfos:      file_database_proto_msgTypes,
	}.Build()
	File_database_proto = out.File
	file_database_proto_goTypes = nil
	file_database_proto_depIdxs = nil
}
